# Generated by Django 3.1.4 on 2020-12-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('yield_kWp', models.IntegerField(verbose_name='Yield in kWh/kWp/a')),
            ],
        ),
    ]
